(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = n => Number.isFinite(n) ? new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n) : '—';
  const num = (n,d=0) => Number.isFinite(n) ? new Intl.NumberFormat('es-ES',{maximumFractionDigits:d}).format(n) : '—';
  const clone = o => JSON.parse(JSON.stringify(o));
  const M = window.WorkshopModel, T = window.WorkshopTechnical, K = window.WorkshopMarket, R = window.WorkshopRoadmap;
  if (!M || !T || !K || !R) { document.body.insertAdjacentHTML('afterbegin','<div class="notice error" role="alert">Falta un archivo del proyecto. Abre la carpeta completa mediante previsualizar.command. El cálculo se ha detenido para evitar resultados incompletos.</div>'); return; }
  const KEY = 'atelier-codex-project-v1';
  const add = (id,name,amount,vatRate,category,reason,depreciable=false) => ({id,name,amount,vatRate,category,reason,financed:false,depreciable,lifeMonths:depreciable?120:0,status:'Presupuesto 2028 · estimación',source:{title:'Estimación de planificación; pendiente de oferta',url:''}});
  function initialInvestments() {
    const equipment = T.equipment.map(item => ({...clone(item),referenceAmount:item.amount,amount:Math.round(item.amount*1.03*1.03),category:item.depreciable?'equipment':'preopening',sourceCategory:item.category,reason:item.reason+' Presupuesto inicial 2028: referencia 2026 incrementada un 3% anual durante dos años; sustituir por oferta real.'}));
    return equipment.concat([
      add('fitout','Obra y adaptación del local',31827,.21,'fitout','Base 2026 de 30.000 € + 3% anual durante dos años. Incluye adecuación eléctrica/ventilación general a definir, no grandes refuerzos ni reconstrucción.',true),
      add('engineering','Proyecto técnico y legalizaciones',4774,.21,'fees','Base 2026 de 4.500 € actualizada al 3% anual. Alcance y honorarios a cotizar.'),
      add('municipal-fees','Tasas y trámites',2500,0,'fees','Reserva de gasto, sin presupuesto municipal. No aplicar IVA automáticamente a tasas.'),
      add('deposit','Fianza y garantías del local',7500,0,'deposit','Fianza/garantía recuperable; importe orientativo. Puede ser mucho mayor según contrato. No se amortiza.'),
      add('stock','Stock inicial de recambios y consumibles',4244,.21,'stock','Fondo de existencias permanente. Se repone según consumo; no se considera gasto íntegro ni beneficio.'),
      add('frontdesk','Recepción sencilla y mobiliario',2100,.21,'equipment','Mobiliario sin reforma de lujo. Informática y bancos de taller ya incluidos en equipo.',true),
      add('signage','Rótulo y señalética comercial',1600,.21,'equipment','Diseño y rotulación independientes; validar marca y permisos.',true),
      add('fire-security','Incendios, intrusión y control de accesos',4500,.21,'equipment','Reserva para dotación a definir en proyecto; revisar solapes con obra. Sistemas exigidos pueden superar este importe.',true),
      add('preparation','Selección, formación y asesoría de preparación',5000,.21,'preopening','Bolsa adicional previa a apertura; no incluye tu curso ya contratado ni gastos personales. IVA presupuestado, revisar por factura.'),
      add('works-overrun','Sobrecoste de instalación previsto',5000,.21,'preopening','Se trata como desembolso y gasto consumido para no inflar la caja. No es la reserva de tesorería; asignar a partidas reales al presupuestar.')
    ]);
  }
  const base = {...clone(M.defaults),investments:initialInvestments(),cashReserveTarget:40000,otherFixed:2200};
  let state = {version:1,config:clone(base),scenarios:[],tasks:{}};
  let result = null;
  function validConfig(c) { return c && typeof c === 'object' && M.validate(c).length===0; }
  try { const stored=JSON.parse(localStorage.getItem(KEY)); if(stored && stored.version===1 && validConfig(stored.config)) {state.config={...clone(base),...stored.config};state.scenarios=Array.isArray(stored.scenarios)?stored.scenarios.filter(s=>typeof s.name==='string'&&validConfig(s.config)).slice(0,100):[];state.tasks=stored.tasks&&typeof stored.tasks==='object'?stored.tasks:{};} } catch (_) {}
  function persist() {try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){$('save-status').textContent='Este navegador no permite guardar. Exporta el proyecto para conservarlo.';}}
  let toastTimer;
  function toast(text) {$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
  const fields = [
    {title:'1 · Equipo y capital',open:true,items:[
      ['owners','Socios que trabajan',1,2,1,'select','Incluye el sueldo de cada socio. El jefe se cuenta aparte.'],
      ['equityPerOwner','Aportación por socio · €',0,200000,1000,'range','Rango indicado: 50.000–120.000 €. Introduce capital comprometible; no una indemnización incierta.'],
      ['ownerCost','Coste total por socio · €/mes',2000,6000,50,'number','Objetivo: 2.000 € netos. Esta bolsa no calcula IRPF ni RETA; validar con asesoría.'],
      ['chiefCost','Coste empresa del jefe · €/mes',3000,9000,50,'number','Hipótesis presupuestaria; contrastar oferta, cotización, pagas y variable.'],
      ['ownerShare','Jornada mecánica del socio · %',0,80,5,'percent','El resto queda para gestión. Se aplica además el rendimiento de aprendizaje.'],
      ['recepMonth','Recepción desde el mes',0,60,1,'number','0 = no contratar. Se activa el coste; no añade demanda ni capacidad mecánica.'],
      ['recepCost','Coste empresa de recepción · €/mes',0,4500,50,'number','Puede representar una jornada parcial si ajustas el coste.']
    ]},
    {title:'2 · Clientes y precios',open:true,items:[
      ['tariff','Mano de obra sin IVA · €/hora',50,180,1,'range','105 € es hipótesis apoyada en tus referencias anteriores, pendiente de confirmar base fiscal.'],
      ['demandStart','Demanda inicial · horas/mes',0,400,5,'range','Horas que los clientes quieren comprar. No se crean al contratar más personal.'],
      ['demandEnd','Demanda al madurar · horas/mes',0,600,5,'range','Se facturará como máximo la capacidad disponible. No es una previsión de mercado demostrada.'],
      ['rampMonths','Meses hasta esa demanda',1,60,1,'number','Crecimiento lineal como hipótesis. Se aplican los factores de vacaciones si están activos.'],
      ['partsRatio','Ventas recambios / mano de obra',0,3,.05,'number','0,67 € de recambios por euro de mano de obra. A contrastar por trabajos.'],
      ['partsMargin','Margen bruto del recambio · %',0,70,1,'percent','Sobre precio de venta. Compra 70 €, venta 100 € = 30%. No confundir con recargo.']
    ]},
    {title:'3 · Horas y aprendizaje',items:[
      ['presence','Presencia mensual por persona · h',40,200,1,'number','Antes de dedicar parte a gestión/formación. Evita descontar vacaciones dos veces.'],
      ['chiefShare','Jornada productiva del jefe · %',30,90,5,'percent','El resto cubre supervisión, diagnosis interna, planificación y calidad.'],
      ['noviceStart','Rendimiento inicial de los socios · %',0,70,5,'percent','Sobre horas dedicadas a mecánica. Hipótesis, no evaluación de competencia.'],
      ['noviceEnd','Rendimiento posterior de los socios · %',20,100,5,'percent','Al final del aprendizaje. Un 80% de jornada × 70% rendimiento son 56% de horas vendibles.'],
      ['noviceMonths','Meses de aprendizaje',1,48,1,'number','Actualizar según experiencia práctica supervisada real.'],
      ['lifts','Elevadores en servicio',0,5,1,'number','Cambiarlo no compra equipos: actualiza la inversión en «Taller y equipo».'],
      ['bayHours','Horas útiles por elevador · mes',40,180,5,'number','Incluye bloqueo, preparación y maniobra; antes del factor de vacaciones.'],
      ['seasonality','Aplicar vacaciones presupuestadas',0,1,1,'select','Reduce demanda y capacidad en agosto y diciembre, manteniendo salarios y alquiler.'],
      ['augustFactor','Actividad de agosto · %',0,100,5,'percent','Supuesto de cierre parcial; no dato histórico demostrado del mercado de Madrid.'],
      ['decemberFactor','Actividad de diciembre · %',0,100,5,'percent','Ajustar a la política de vacaciones.']
    ]},
    {title:'4 · Local y gastos',items:[
      ['rent','Alquiler y gastos del local · €/mes',0,7000,100,'number','Incluir comunidad e IBI repercutido cuando proceda. Revisar IVA real por concepto.'],
      ['otherFixed','Otros costes fijos · €/mes',0,7000,50,'number','Diagnosis, suministros, seguros, gestoría, software, residuos, prevención, limpieza y mantenimiento.'],
      ['marketing','Captación y marketing · €/mes',0,2500,50,'number','Es presupuesto de trabajo, no una garantía de clientes.'],
      ['annualInflation','Aumento anual de costes · %',0,15,.5,'percent','A partir del año 2 de operación; la tarifa permanece fija para no suponer subidas aceptadas.'],
      ['warrantyRate','Garantías / retrabajos · % ventas',0,10,.5,'percent','Se reconoce gasto y se presupone consumo de caja mensual equivalente.'],
      ['cashReserveTarget','Reserva mínima objetivo · €',0,150000,1000,'number','Objetivo de caja; no es una inversión ni un gasto. Base 40.000 €, revisar según gastos y riesgo.']
    ]},
    {title:'5 · Financiación',items:[
      ['loan','Préstamo general / posible ICO · €',0,200000,1000,'range','Desembolso supuesto en apertura. La concesión y garantías dependen del banco.'],
      ['loanAPR','Interés nominal préstamo · %',0,20,.25,'percent','Hipótesis futura; comisiones iniciales deben añadirse al presupuesto.'],
      ['loanMonths','Plazo total préstamo · meses',12,120,1,'number','Incluye la carencia; el principal se devuelve dentro de este plazo.'],
      ['graceMonths','Carencia de principal · meses',0,24,1,'number','Durante carencia se pagan intereses. Debe ser menor que el plazo.'],
      ['equipmentFinanceAPR','Interés equipo financiado · %',0,20,.25,'percent','Préstamo por precio neto de las partidas marcadas. No renting ni leasing fiscal.'],
      ['equipmentFinanceMonths','Plazo equipo · meses',12,120,1,'number','Las cuotas dejan de cobrarse al vencer.']
    ]},
    {title:'6 · Apertura y tesorería',items:[
      ['openingDate','Mes de apertura',0,0,0,'month','Septiembre 2028 objetivo; junio como mínimo planteado, no garantizado.'],
      ['horizon','Meses de proyección',12,60,12,'number','Los indicadores anuales utilizan los últimos doce meses.'],
      ['preopeningMonths','Meses preparando el local',0,12,1,'number','Alquiler y personal pagados antes de generar ventas. No representa los dos años completos de estudio.'],
      ['preopeningStaffCost','Personal de preparación · €/mes',0,16000,100,'number','Bolsa media mensual. Ej.: un mes del jefe y apoyo repartidos en tres meses. Añade vuestros sueldos si ya habéis dejado el empleo.'],
      ['customerDays','Cobro a clientes · días',0,60,1,'number','0 = cobrar al entregar. El plazo reparte cobros entre meses; no modela impagos.'],
      ['supplierDays','Pago de recambios · días',0,60,1,'number','Usar 0 hasta confirmar crédito del proveedor. El crédito comercial no equivale a margen.'],
      ['taxRate','Provisión de impuesto · %',0,35,1,'percent','Tipo plano de planificación. No calcula tu régimen fiscal: 2028 y posibles tipos reducidos requieren validación.'],
      ['otherFixedVatShare','Otros costes sujetos a IVA · %',0,100,5,'percent','Aproximación de mezcla de gastos; nóminas/seguros no se gravan automáticamente al 21%.']
    ]}
  ];
  const fieldIndex = new Map(fields.flatMap(g=>g.items).map(f=>[f[0],f]));
  function renderFields() {
    $('fields').innerHTML=fields.map(g=>`<details ${g.open?'open':''}><summary>${esc(g.title)}</summary>${g.items.map(f=>{
      const [key,label,min,max,step,type,help]=f;let v=state.config[key];if(type==='percent')v=Math.round(v*10000)/100;if(type==='month')v=v.slice(0,7);
      let control=type==='select'?`<select id="f-${key}" data-field="${key}">${key==='owners'?`<option value="1" ${v===1?'selected':''}>1 socio + jefe</option><option value="2" ${v===2?'selected':''}>2 socios + jefe</option>`:`<option value="1" ${v===1?'selected':''}>Sí</option><option value="0" ${v===0?'selected':''}>No</option>`}</select>`:`<input id="f-${key}" data-field="${key}" type="${type==='month'?'month':'number'}" ${type==='month'?'min="2028-06" max="2032-12"':`min="${min}" max="${max}" step="${step}"`} value="${esc(v)}">`;
      if(type==='range')control=`<div class="input-wrap"><input type="range" aria-label="${esc(label)}" data-field="${key}" min="${min}" max="${max}" step="${step}" value="${v}">${control}</div>`;
      return `<label class="field ${type==='range'?'dual':''}" for="f-${key}"><span>${esc(label)}</span>${control}<small>${esc(help)}</small></label>`;
    }).join('')}</details>`).join('');
  }
  function row(label,value,negative=false) {return `<div class="data-row"><span>${esc(label)}</span><b class="${negative?'negative':''}">${value}</b></div>`;}
  function metric(label,value,note,negative=false) {return `<div class="metric"><span>${esc(label)}</span><b class="${negative?'negative':''}">${value}</b><small>${esc(note)}</small></div>`;}
  function verdict(s) {if(s.lowestCash<0)return {cls:'bad',title:'Falta caja en este escenario',tag:'REQUIERE CAMBIOS'};if(s.lowestCash<s.reserveTarget)return {cls:'warn',title:'Sobrevive, pero consume la reserva',tag:'MARGEN DE SEGURIDAD BAJO'};if(s.annualProfit<0)return {cls:'warn',title:'Hay caja, pero el taller sigue en pérdidas',tag:'REVISAR OPERACIÓN'};return {cls:'',title:'Caja suficiente bajo estos supuestos',tag:'DEMANDA Y COSTES POR VALIDAR'};}
  function renderResults() {
    const errors=M.validate(state.config);
    if(errors.length){$('model-errors').hidden=false;$('model-errors').textContent='No se ha actualizado el cálculo: '+errors.join(' ');return false;}
    $('model-errors').hidden=true;result=M.simulate(state.config);const s=result.summary,last=result.months.at(-1),v=verdict(s);
    $('diagnosis').className='diagnosis '+v.cls;
    $('diagnosis').innerHTML=`<span class="eyebrow">${v.tag}</span><h2>${v.title}</h2><p>${s.additionalFunding>0?`Para mantener ${money(s.reserveTarget)} de reserva harían falta ${money(s.additionalFunding)} de aportación adicional, manteniendo la deuda actual.`:`La caja mínima supera la reserva en ${money(s.lowestCash-s.reserveTarget)}.`} ${s.annualProfit<0?'Más dinero no corrige por sí solo las pérdidas del negocio.':'Esto no acredita una cartera de clientes ni financiación aprobada.'}</p>`;
    $('metrics').innerHTML=metric('Caja mínima',money(s.lowestCash),s.minimumCashLabel,s.lowestCash<0)+metric('Capital propio necesario',money(s.requiredEquity),'Total, con reserva y deuda configuradas')+metric('Beneficio últimos 12 meses',money(s.annualProfit),'Después del coste de todos los sueldos',s.annualProfit<0)+metric('Equilibrio contable',num(s.breakEvenHours)+' h','Al mes, con costes del último mes');
    $('funding').innerHTML=row('Inversión / gastos iniciales netos',money(s.totalInvestment))+row('IVA inicial inversión y alquiler previo',money(s.investmentVAT+s.preopeningVAT))+row('Alquiler y personal antes de abrir',money(s.preopeningCost))+row('Equipo a crédito (neto)',money(s.financedEquipment))+row('Aportación total de socios',money(s.totalEquity))+row('Préstamo general supuesto',money(state.config.loan))+row('Caja al abrir',money(s.initialCash),s.initialCash<0)+row('Cuota deuda tras carencia',money(s.monthlyDebtAfterGrace)+'/mes')+row('Deuda pendiente al final',money(s.lastDebt));
    $('capacity').innerHTML=row('Demanda · '+last.label,num(last.demand)+' h/mes')+row('Capacidad · '+last.label,num(last.capacity)+' h/mes')+row('Horas facturadas · primer / último mes',num(result.months[0].hours)+' / '+num(last.hours))+row('Equilibrio de caja (sin IVA/IS)',num(s.cashBreakEvenHours)+' h/mes')+row('3 meses seguidos de beneficio',s.sustainedBreakEvenMonth?esc(result.months[s.sustainedBreakEvenMonth-1].label):'No alcanzado')+`<p class="small">${s.breakEvenHours>last.capacity?'En el último mes proyectado, la capacidad disponible no alcanza el equilibrio contable; revisa su factor de vacaciones. ':''}${last.unservedHours>0?`Quedan ${num(last.unservedHours)} horas de demanda sin atender en el último mes. `:''}La capacidad no sustituye a la demanda. La supervisión y calidad pueden limitarla más que este cálculo.</p>`;
    renderChart();renderSensitivity();renderComparison();renderMonthly();renderInvestmentTotal();renderChief();persist();return true;
  }
  function renderChart() {
    const c=state.config,s=result.summary,values=[s.initialCash,...result.months.map(m=>m.cash)];const width=760,height=290,p={l:62,r:20,t:20,b:35};
    let low=Math.min(0,...values),high=Math.max(c.cashReserveTarget,...values);const span=Math.max(20000,high-low);low-=span*.08;high+=span*.10;
    const x=i=>p.l+i/(values.length-1)*(width-p.l-p.r),y=v=>p.t+(high-v)/(high-low)*(height-p.t-p.b);
    const ticks=Array.from({length:5},(_,i)=>low+(high-low)*i/4);
    const line=values.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(v).toFixed(2)}`).join(' ');
    const area=line+` L${x(values.length-1)},${y(0)} L${x(0)},${y(0)}Z`;
    $('cash-chart').innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Evolución de caja. Mínimo ${money(s.lowestCash)}, final ${money(s.endingCash)}"><defs><linearGradient id="cashfill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#769572" stop-opacity=".25"/><stop offset="1" stop-color="#769572" stop-opacity=".02"/></linearGradient></defs>${ticks.map(t=>`<line x1="${p.l}" y1="${y(t)}" x2="${width-p.r}" y2="${y(t)}" stroke="#e5e8df"/><text x="${p.l-10}" y="${y(t)+3}" text-anchor="end" fill="#84907f" font-size="10">${num(t/1000)} mil</text>`).join('')}<line x1="${p.l}" y1="${y(0)}" x2="${width-p.r}" y2="${y(0)}" stroke="#b26a58" stroke-width="1"/><line x1="${p.l}" y1="${y(c.cashReserveTarget)}" x2="${width-p.r}" y2="${y(c.cashReserveTarget)}" stroke="#bc9654" stroke-dasharray="5 5"/><path d="${area}" fill="url(#cashfill)"/><path d="${line}" stroke="#315b44" stroke-width="2.5" fill="none"/>${values.map((value,i)=>i%6===0||i===values.length-1?`<text x="${x(i)}" y="${height-10}" text-anchor="middle" fill="#84907f" font-size="10">${i===0?'Apertura':esc(result.months[i-1].label)}</text>`:'').join('')}<circle cx="${x(s.lowestMonth)}" cy="${y(s.lowestCash)}" r="4.5" fill="${s.lowestCash<0?'#a44136':'#315b44'}"/></svg>`;
    $('chart-month').max=result.months.length;if(Number($('chart-month').value)>result.months.length)$('chart-month').value=result.months.length;renderChartDetail();
  }
  function renderChartDetail() {if(!result)return;const i=Number($('chart-month').value),m=i?result.months[i-1]:null;$('cash-detail').innerHTML=`<strong>${m?esc(m.label):'Antes de abrir'}</strong><span>Caja <b class="${(m?m.cash:result.summary.initialCash)<0?'negative':''}">${money(m?m.cash:result.summary.initialCash)}</b></span><span>${m?'Resultado '+money(m.netProfit):'Tras inversión y preparación'}</span>`;}
  function renderComparison() {$('owner-comparison').innerHTML=[1,2].map(owners=>{const s=M.simulate({...state.config,owners}).summary,v=verdict(s);return `<article class="card"><div class="compare-title"><h3>${owners} ${owners===1?'socio':'socios'} + jefe</h3><span class="pill ${v.cls?'amber':''}">${s.lowestCash<0?'FALTA CAJA':s.annualProfit<0?'PÉRDIDAS':s.lowestCash<s.reserveTarget?'POCO COLCHÓN':'CAJA SUFICIENTE'}</span></div>${row('Aportación total',money(s.totalEquity))}${row('Menor saldo de caja',money(s.lowestCash),s.lowestCash<0)}${row('Beneficio últimos 12 meses',money(s.annualProfit),s.annualProfit<0)}${row('Capital requerido por socio',money(s.requiredEquity/owners))}<p class="small">${owners===1?'Decisión y gestión concentradas; menos sueldos fijos. Más dependencia del jefe y menor capacidad de reparación.':'Aporta más caja y capacidad, pero cada sueldo empieza desde el día uno. Requiere funciones y pacto de socios.'}</p><a href="#simulador" data-owners="${owners}">Explorar esta estructura →</a></article>`;}).join('');}
  function renderSensitivity() {
    const c=state.config,checks=[['Escenario actual',{}],['Demanda −25%',{demandStart:c.demandStart*.75,demandEnd:c.demandEnd*.75}],['Tarifa −10%',{tariff:c.tariff*.9}],['Obra +30% y 3 meses de retraso',{preopeningMonths:c.preopeningMonths+3,investments:c.investments.map(a=>({...a,amount:a.id==='fitout'?a.amount*1.3:a.amount}))}],['Sin crédito bancario ni de equipo',{loan:0,investments:c.investments.map(a=>({...a,financed:false}))}],['Recepción desde el mes 4',{recepMonth:4}]];
    $('sensitivity').innerHTML=`<table><thead><tr><th>Prueba</th><th class="num">Caja mínima</th><th class="num">Capital extra para reserva</th></tr></thead><tbody>${checks.map(([name,patch])=>{const s=M.simulate({...c,...patch}).summary;return `<tr><td>${esc(name)}</td><td class="num ${s.lowestCash<0?'negative':''}">${money(s.lowestCash)}</td><td class="num">${money(s.additionalFunding)}</td></tr>`;}).join('')}</tbody></table>`;
  }
  function renderMonthly() {const cols=[['Mes','label'],['Horas','hours'],['Ventas','revenue'],['Piezas (coste)','partsCost'],['Personal','staffCost'],['Recepción','receptionCost'],['Resultado operativo¹','ebitda'],['Amortización','depreciation'],['Intereses','interest'],['Impuesto devengado','taxAccrued'],['Beneficio neto','netProfit'],['IVA pagado','vatPayment'],['Impuesto pagado','taxPayment'],['Principal devuelto','principal'],['Variación caja','cashChange'],['Caja','cash'],['Deuda','loans']];$('monthly-table').innerHTML=`<table><thead><tr>${cols.map(([name])=>`<th>${esc(name)}</th>`).join('')}</tr></thead><tbody>${result.months.map(m=>`<tr>${cols.map(([,key])=>`<td class="${key==='label'?'':'num'} ${m[key]<0?'negative':''}">${key==='label'?esc(m[key]):key==='hours'?num(m[key],1):money(m[key])}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="small">¹ Antes de amortización, intereses e impuesto. El IVA pendiente, impuesto pendiente y saldos comerciales están en la exportación CSV. Caja final no equivale a dinero libre de obligaciones.</p>`;}
  function sourceLink(s,label) {if(!s || !s.url)return `<span class="small">${esc(s&&s.title||'Estimación propia')}</span>`;if(!/^(https?:\/\/|\.\.\/data\/)/.test(s.url))return '';return `<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(label||s.title)} ↗</a>`;}
  function renderEquipment() {$('equipment').innerHTML=`<table><thead><tr><th>Partida y criterio</th><th>Referencia</th><th class="num">Presupuesto neto €</th><th>IVA %</th><th>A crédito</th></tr></thead><tbody>${state.config.investments.map((a,i)=>`<tr><td><strong>${esc(a.name)}</strong><small>${esc(a.reason||'Partida importada: revisar presupuesto y tratamiento.')}</small>${a.exclusions?`<details><summary class="small">Qué falta confirmar</summary><small>${esc(a.exclusions)}</small></details>`:''}</td><td><span class="pill ${a.status==='Precio público'?'':'amber'}">${a.status==='Precio público'?'PRECIO 2026':'ESTIMACIÓN'}</span>${a.referenceAmount?`<small>${money(a.referenceAmount)} base 2026</small>`:''}${sourceLink(a.source)}</td><td class="num"><input aria-label="Importe ${esc(a.name)}" data-invest="${i}" data-prop="amount" type="number" min="0" max="1000000" step="1" value="${a.amount}"></td><td><input style="width:65px" aria-label="IVA ${esc(a.name)}" data-invest="${i}" data-prop="vatRate" type="number" min="0" max="100" step="1" value="${Math.round(a.vatRate*100)}"></td><td><input aria-label="Financiar ${esc(a.name)}" data-invest="${i}" data-prop="financed" type="checkbox" ${a.financed?'checked':''}></td></tr>`).join('')}</tbody></table>`;}
  function renderInvestmentTotal() {if(!result)return;const s=result.summary;$('investment-total').innerHTML=metric('Presupuesto neto',money(s.totalInvestment),'Equipo, obra, preparación y fianza')+metric('Equipo financiado',money(s.financedEquipment),'Sujeto a aceptación de la entidad')+metric('IVA inicial',money(s.investmentVAT),'Se paga al inicio, no se regala')+metric('Preparación del local',money(s.preopeningCost),'Alquiler + personal, sin IVA');}
  function renderChief() {const sal=K.salary;$('chief-budget').innerHTML=`<p>Presupuesto de búsqueda: <strong>${money(sal.grossLow)}–${money(sal.grossHigh)} brutos/año</strong>; probar también ${money(sal.stressGross)}. Hipótesis para un perfil experimentado, no tarifa Porsche confirmada.</p><p>En tu escenario: <strong>${money(state.config.chiefCost)} al mes de coste empresa</strong>. Para socios: ${money(state.config.ownerCost)} por persona como bolsa para el objetivo de 2.000 € netos.</p><p class="small">${esc(sal.caveat)}</p><div class="source-links">${sal.sources.slice(0,2).map(s=>sourceLink(s)).join('')}</div>`;}
  function renderMarket() {
    $('market-recommendation').innerHTML=`<article class="card recommendation"><span class="eyebrow">ORDEN DE BÚSQUEDA PROPUESTO</span><h2>Norte y noroeste, con el sur como control.</h2><p>${esc(K.decision)}</p><p class="small">El primer estudio es una preselección. No hay base suficiente para elegir un municipio definitivo ni para afirmar que existe un hueco sin competencia.</p></article>`;
    $('areas').innerHTML=K.areas.map(a=>`<article class="card area-card"><div class="area-top"><h3>${esc(a.name)}</h3><span class="pill muted">PARQUE 2026</span></div><div class="area-number">${num(a.count)}</div><p class="small">${esc(a.coverage)}</p><p>${esc(a.assessment)}</p><p class="small"><strong>Renta observada:</strong> ${a.rentLow!==null?money(a.rentLow)+(a.rentHigh!==a.rentLow?'–'+money(a.rentHigh):'')+'/mes':'Sin comparable verificado'}. ${esc(a.rentBasis)}</p><p class="small">${a.municipalities.map(m=>`${esc(m.name)}: ${num(m.count)}`).join(' · ')}</p><div class="source-links">${a.sources.filter(s=>s.url.startsWith('http')).slice(0,3).map(s=>sourceLink(s)).join('')}</div></article>`).join('');
    $('competitors').innerHTML=`<table><thead><tr><th>Taller</th><th>Ubicación</th><th>Servicios y lectura</th></tr></thead><tbody>${K.competitors.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small>${esc(c.type)}</small></td><td>${esc(c.location)}</td><td>${esc(c.specialty)}<small>${esc(c.implication)}</small>${c.sources.map(s=>sourceLink(s)).join(' · ')}</td></tr>`).join('')}</tbody></table>`;
    const tr=K.transferExample;
    $('rent-listings').innerHTML=`<h3>Lo que enseñan los anuncios consultados</h3><div class="table-wrap"><table><thead><tr><th>Anuncio</th><th class="num">Renta base</th><th class="num">Total / planta baja</th><th>Lo que cambia la decisión</th></tr></thead><tbody>${K.listings.map(l=>`<tr><td>${sourceLink(l.sources[0],l.name)}</td><td class="num">${money(l.rentMonthly)}/mes</td><td class="num">${num(l.builtM2)} / ${num(l.groundM2)} m²</td><td>${esc(l.caveat)}${l.additionalGuarantee?`<small>Garantía adicional anunciada: ${money(l.additionalGuarantee)}; fianza ${money(l.deposit)}. Gasto recurrente calculado antes de impuestos: ${money(l.recurringMonthlyBeforeTax)}.</small>`:''}</td></tr>`).join('')}</tbody></table></div><p class="small">${esc(K.dataCaveat)}</p><p><strong>Ejemplo de traspaso:</strong> ${sourceLink(tr.sources[0],tr.name)}. ${money(tr.price)} de entrada + ${money(tr.rentMonthly)}/mes, ${num(tr.builtM2)} m² totales. Fuera del tamaño buscado y con inversión elevada para vuestro rango. Este anuncio no permite descartar todos los traspasos.</p>`;
  }
  const scopeCards=[{title:'Desde apertura, con competencia demostrada',items:['Mantenimiento de Porsche térmicos seleccionados por generación.','Frenos, suspensión, refrigeración y averías acotadas.','Diagnosis y PPI con documentación, acceso y supervisión adecuados.']},{title:'Colaboradores y límites técnicos',items:['Neumáticos, alineación y ADAS inicialmente con colaboradores.','Climatización regulada solo con acreditación y equipo; subcontratar al inicio.','Motores/cajas, restauración y pintura compleja fuera del arranque.']},{title:'Expansión que debe ganarse',items:['Audi/VAG solo por generación, sistema y capacidad real del equipo. Compartir marca de grupo no garantiza compatibilidad.','En híbridos/eléctricos, aceptar solo tareas permitidas por evaluación y procedimiento. Sin intervención en propulsión de alta tensión.','Compraventa después de calidad estable y caja demostrada, con capital separado.']}];
  function renderScope() {$('scope').innerHTML=scopeCards.map(c=>`<article class="card scope-card"><h3>${c.title}</h3><ul>${c.items.map(t=>`<li>${t}</li>`).join('')}</ul></article>`).join('')+`<div class="notice" style="grid-column:1/-1">Panamera y RS6 no son intercambiables: las referencias actuales consultadas describen PDK y tiptronic respectivamente. La aceptación se decide por VIN, sistema, procedimiento y herramientas. ${sourceLink(T.sources.find(s=>s.id==='panamera-pdk'),'Porsche Panamera')} · ${sourceLink(T.sources.find(s=>s.id==='rs6-tiptronic'),'Audi RS6')} · ${sourceLink(T.sources.find(s=>s.id==='insst-electrical'),'Riesgo eléctrico')}</div>`;}
  function taskHTML(t) {return `<label class="task ${state.tasks[t.id]?'done':''}"><input data-task="${esc(t.id)}" type="checkbox" ${state.tasks[t.id]?'checked':''}><span><strong>${esc(t.name)}</strong>${t.detail?`<small>${esc(t.detail)}</small>`:''}</span></label>`;}
  function renderRoadmap() {$('next-actions').innerHTML=R.next.map(taskHTML).join('');$('roadmap').innerHTML=R.stages.map(s=>`<section class="road-stage"><div class="road-date">${esc(s.date)}<small>${esc(s.subtitle)}</small></div><article class="card"><h3>${esc(s.title)}</h3><p class="small"><strong>Responsable:</strong> ${esc(s.owner)}</p><p><strong>Resultado esperado:</strong> ${esc(s.deliverable)}</p>${s.tasks.map(taskHTML).join('')}<div class="notice"><strong>Condición de avance:</strong> ${esc(s.condition)}</div></article></section>`).join('');$('gates').innerHTML=R.gates.map((g,i)=>`<article class="card"><div class="gate-number">0${i+1}</div><h3>${esc(g.title)}</h3><p>${esc(g.text)}</p></article>`).join('');const all=R.next.concat(R.stages.flatMap(s=>s.tasks));$('roadmap-progress').textContent=`${all.filter(t=>state.tasks[t.id]).length} / ${all.length} ACCIONES COMPLETADAS`;}
  function renderSources() {
    $('assumptions').innerHTML='<ol>'+M.simulate(state.config).assumptions.map(a=>`<li>${esc(a)}</li>`).join('')+'</ol><p class="small">El escenario presupone una sociedad para ilustrar impuesto sobre beneficios. El régimen real, cotizaciones de socios y tratamiento de cada contrato quedan pendientes de gestoría. La caja puede contener IVA, impuestos, garantías y pagos a proveedores todavía pendientes.</p>';
    const fiscal=[{title:'AEAT · devolución y compensación del IVA',url:'https://sede.agenciatributaria.gob.es/Sede/iva/obtener-devolucion-iva/solicitar-devolucion.html',type:'Oficial',note:'El saldo negativo no es un cobro automático al cuarto mes.'},{title:'AEAT · tipos de gravamen',url:'https://sede.agenciatributaria.gob.es/Sede/ayuda/manuales-videos-folletos/manuales-practicos/manual-sociedades-2025/principales-novedades-impuesto-sobre-sociedades-2025/tipos-gravamen.html',type:'Oficial',note:'Existen tipos y requisitos distintos. El 20% plano del simulador es una provisión editable, no el tipo legal personalizado.'}];
    const marketSources=K.areas.flatMap(a=>a.sources).concat(K.competitors.flatMap(c=>c.sources),K.listings.flatMap(l=>l.sources),K.salary.sources).filter(s=>s.url.startsWith('http'));
    const dedup=sources=>[...new Map(sources.map(s=>[s.url,s])).values()];
    $('source-list').innerHTML=[['Formación, requisitos y equipo',T.sources],['Mercado, locales y contratación',dedup(marketSources)],['Fiscalidad',fiscal]].map(([title,sources])=>`<section class="source-group card"><h2>${title}</h2>${sources.map(s=>`<div class="source-entry"><div>${sourceLink(s)}<p>${esc(s.note||'Consultada en septiembre de 2026. Actualizar antes de la apertura.')}</p></div><span class="pill muted">${esc(s.type||'REFERENCIA PÚBLICA')}</span></div>`).join('')}</section>`).join('');
  }
  function renderSaved() {$('saved-scenarios').innerHTML='<option value="">Escenarios guardados…</option>'+state.scenarios.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('');}
  function switchPage() {let id=location.hash.slice(1)||'decision';if(!['decision','simulador','calendario','ubicacion','taller','fuentes'].includes(id))id='decision';document.querySelectorAll('.page').forEach(el=>{el.hidden=el.id!==id;el.classList.toggle('active',el.id===id);});document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));const selected=document.querySelector('.sidebar nav a.active');$('breadcrumb').textContent=selected?selected.textContent.replace(/^\d+\s*/,'').trim():'La decisión';window.scrollTo(0,0);}
  function download(name,text,type) {const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportProject() {if(!validConfig(state.config)){toast('Corrige los datos antes de exportar.');return;}download('atelier-proyecto-2028.json',JSON.stringify({...state,exportedAt:new Date().toISOString(),scope:'Planificación privada; precios y demanda por validar'},null,2),'application/json');toast('Copia de proyecto descargada.');}
  function exportCSV() {if(!result || !validConfig(state.config)){toast('Corrige los datos antes de exportar.');return;}const keys=Object.keys(result.months[0]);const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const text=[keys.map(cell).join(';'),...result.months.map(m=>keys.map(k=>cell(typeof m[k]==='number'?Number(m[k].toFixed(2)).toString().replace('.',','):m[k])).join(';'))].join('\r\n');download('atelier-meses.csv','\uFEFF'+text,'text/csv;charset=utf-8');toast('Tabla mensual descargada.');}
  function setPreset(name) {let patch={};if(name==='duo')patch={owners:2};if(name==='stress')patch={demandStart:40,demandEnd:170,rampMonths:30};if(name==='high')patch={demandStart:100,demandEnd:320,rampMonths:18,owners:2};state.config={...clone(base),...patch};document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',b.dataset.preset===name));renderFields();renderEquipment();renderResults();toast('Escenario de partida cargado. Guarda los cambios para conservar otra variante.');}
  function handleChange(e) {
    const target=e.target;
    if(target.dataset.field){const key=target.dataset.field,f=fieldIndex.get(key);let value=f[5]==='month'?target.value+'-01':Number(target.value);if(f[5]==='percent')value/=100;state.config[key]=value;document.querySelectorAll(`[data-field="${key}"]`).forEach(el=>{if(el!==target)el.value=target.value;});document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('selected'));renderResults();}
    if(target.dataset.invest!==undefined){const item=state.config.investments[Number(target.dataset.invest)],prop=target.dataset.prop;item[prop]=prop==='financed'?target.checked:prop==='vatRate'?Number(target.value)/100:Number(target.value);renderResults();}
    if(target.dataset.task){state.tasks[target.dataset.task]=target.checked;persist();renderRoadmap();}
  }
  document.addEventListener('input',handleChange);
  document.addEventListener('change',handleChange);
  document.addEventListener('click',e=>{const preset=e.target.closest('[data-preset]');if(preset)setPreset(preset.dataset.preset);const owner=e.target.closest('[data-owners]');if(owner){state.config.owners=Number(owner.dataset.owners);renderFields();renderResults();}});
  $('chart-month').addEventListener('input',renderChartDetail);
  $('save-scenario').addEventListener('click',()=>{const name=$('scenario-name').value.trim();if(!name){$('save-status').textContent='Escribe un nombre para guardar el escenario.';return;}if(!validConfig(state.config)){toast('Corrige los datos del escenario.');return;}state.scenarios.push({name,config:clone(state.config),createdAt:new Date().toISOString()});persist();renderSaved();$('scenario-name').value='';$('save-status').textContent='Escenario guardado en este navegador.';});
  $('load-scenario').addEventListener('click',()=>{const value=$('saved-scenarios').value;if(value===''){toast('Selecciona un escenario guardado.');return;}const item=state.scenarios[Number(value)];if(item){state.config=clone(item.config);renderFields();renderEquipment();renderResults();document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('selected'));toast('Cargado: '+item.name);}});
  $('export-all').addEventListener('click',exportProject);$('export-csv').addEventListener('click',exportCSV);
  $('reset-investments').addEventListener('click',()=>{state.config.investments=initialInvestments();renderEquipment();renderResults();toast('Presupuesto de inversión restaurado.');});
  $('import-project').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3e6)throw new Error('El archivo es demasiado grande.');const data=JSON.parse(await file.text());if(data.version!==1||!validConfig(data.config))throw new Error('Usa una exportación válida de esta versión. Los escenarios antiguos tienen otro modelo.');state.config={...clone(base),...data.config};state.scenarios=Array.isArray(data.scenarios)?data.scenarios.filter(s=>typeof s.name==='string'&&validConfig(s.config)).slice(0,100):[];state.tasks=data.tasks&&typeof data.tasks==='object'?data.tasks:{};renderFields();renderEquipment();renderSaved();renderRoadmap();renderResults();toast('Proyecto importado.');}catch(error){$('save-status').textContent='No se ha importado: '+error.message;toast('No se ha importado el archivo.');}finally{e.target.value='';}});
  window.addEventListener('hashchange',switchPage);
  renderFields();renderEquipment();renderMarket();renderScope();renderRoadmap();renderSaved();renderSources();renderResults();switchPage();
})();
