window.WorkshopRoadmap = {
  next: [
    {id:'study-path',name:'Confirmar por escrito la vía de titulación',detail:'Carlos · antes del 30 sep 2026. Pedir a MasterD: contrato, convocatoria objetivo, módulos, prácticas/FCT o formación en empresa y proyecto; contrastar con el centro público examinador.'},
    {id:'capital',name:'Separar dinero disponible, esperado y reserva personal',detail:'Cada posible socio · antes del 15 oct 2026. Ahorros líquidos, indemnización aún incierta, gastos personales y cantidad máxima comprometible. No contar el ICO como concedido.'},
    {id:'experience',name:'Buscar experiencia práctica supervisada',detail:'Carlos · septiembre–octubre. Contactar 5 talleres para conocer opciones de prácticas o trabajo compatible. No ofrecer reparaciones a clientes sin organización y supervisión adecuadas.'},
    {id:'interviews',name:'Entrevistar a los primeros 10 propietarios',detail:'Carlos y posible socio · antes del 15 oct. Escuchar necesidades sin vender una apertura aún no confirmada. Registrar gasto, frecuencia, tiempos y motivo de elección de taller.'},
    {id:'partner',name:'Acordar qué implicaría emprender juntos',detail:'Ambos · octubre. Aportación, dedicación, sueldo, responsabilidades, salida, desacuerdos y sustituciones. Escribir un borrador antes de invertir juntos.'}
  ],
  stages: [
    {date:'Sep–dic 2026',subtitle:'COMPRENDER EL OFICIO',title:'Formación, realidad personal y primera demanda',owner:'Carlos + posible socio',deliverable:'Ficha de titulación contrastada; presupuesto personal; 25–30 entrevistas documentadas; selección de vías prácticas.',condition:'Continuar si la experiencia real de taller confirma el interés y existe tiempo para formarse.',tasks:[{id:'fp-plan',name:'Concretar convocatoria, calendario académico y práctica supervisada'},{id:'customer-notes',name:'Completar entrevistas y recopilar facturas anonimizadas'},{id:'role-fit',name:'Registrar fortalezas de gestión y habilidades técnicas por adquirir'}]},
    {date:'Ene–mar 2027',subtitle:'DEL OFICIO AL SERVICIO',title:'Elegir trabajos y construir el primer presupuesto',owner:'Promotores + asesor técnico independiente',deliverable:'10 trabajos tipo con tiempo, piezas, tarifa, margen y límites; comparación 1/2 socios; lista de 3 zonas.',condition:'El catálogo inicial debe poder ejecutarse con un experto y socios aprendices.',tasks:[{id:'job-cards',name:'Costear diez órdenes tipo: revisión, frenos, suspensión, refrigeración y diagnosis'},{id:'scope-first',name:'Definir trabajos propios y red de derivación'},{id:'zones-first',name:'Visitar polígonos y comparar accesos, competencia y planta útil'}]},
    {date:'Abr–jun 2027',subtitle:'PRUEBA OPERATIVA',title:'Aprender a producir y medir costes',owner:'Promotores + tutor de prácticas',deliverable:'Registro de tareas supervisadas, calidad y tiempos; tres referencias de equipo; primera conversación bancaria.',condition:'Recalcular si el aprendizaje, los costes o las condiciones de deuda difieren del supuesto.',tasks:[{id:'practice-log',name:'Revisar trimestralmente autonomía técnica con el tutor'},{id:'equipment-offers',name:'Obtener presupuestos comparables con IVA, instalación, formación y soporte'},{id:'bank-first',name:'Consultar financiación, aportación exigida y garantías sin asumir aprobación'}]},
    {date:'Jul–sep 2027',subtitle:'ENCONTRAR AL RESPONSABLE',title:'Jefe de taller y propuesta al cliente',owner:'Carlos',deliverable:'3–5 conversaciones con candidatos, rango salarial real, matriz de habilidades y plan de sustitución; mensajes de captación contrastados.',condition:'No avanzar a un compromiso inmobiliario sin una vía creíble para incorporar al experto.',tasks:[{id:'chief-shortlist',name:'Identificar candidatos y verificar experiencia Porsche y referencias'},{id:'diagnosis-route',name:'Confirmar acceso legal a documentación y diagnosis para los modelos elegidos'},{id:'service-promise',name:'Probar propuesta de valor y registrar interés real de clientes'}]},
    {date:'Oct–dic 2027',subtitle:'DECISIÓN DE INVERSIÓN',title:'Comparar locales y cerrar el escenario financiable',owner:'Promotores + técnico competente + gestoría',deliverable:'3 locales o traspasos comparables, informe de compatibilidad previo, coste completo, escenario adverso y pacto de socios.',condition:'Fondos propios acreditados; deuda preestudiada; caja positiva con menor demanda y retraso de obra.',tasks:[{id:'site-study',name:'Visita técnica: uso, accesos, estructura, potencia, incendios, ventilación y residuos'},{id:'three-sites',name:'Comparar tres alternativas incluyendo al menos un traspaso documentado'},{id:'investment-gate',name:'Decidir seguir, reducir alcance o aplazar con cifras actualizadas'}]},
    {date:'Ene–mar 2028',subtitle:'CONCRETAR SIN IMPROVISAR',title:'Formalización, local y proyecto técnico',owner:'Promotores + jefe seleccionado + especialistas',deliverable:'Acuerdo de incorporación del jefe, financiación aprobada, contrato del local condicionado según asesoramiento, proyecto y trámites aplicables.',condition:'No encadenar firma, obras y pedidos a una indemnización o préstamo aún inciertos.',tasks:[{id:'chief-agreement',name:'Formalizar incorporación y periodo de preparación'},{id:'funding-approved',name:'Disponer de aprobación, costes y garantías documentados'},{id:'site-contract',name:'Formalizar local y tramitar obras/actividad por la vía municipal aplicable'}]},
    {date:'Abr–jun 2028',subtitle:'PREPARAR EL TALLER',title:'Obra, instalaciones, equipo y procesos',owner:'Técnico + instaladores + jefe + promotores',deliverable:'Instalaciones verificadas, equipos documentados, seguros, prevención, residuos, suministros y software; formación práctica del equipo.',condition:'Junio solo es posible si todas las condiciones están cerradas. Exámenes aprobados no equivalen automáticamente al título emitido.',tasks:[{id:'works',name:'Ejecutar obra y comprobar instalaciones y maquinaria'},{id:'operations',name:'Preparar recepción, presupuestos, calidad, garantías y protección de datos'},{id:'providers',name:'Cerrar recambios, subcontratas, seguros y gestión de residuos'}]},
    {date:'Jul–ago 2028',subtitle:'ENSAYAR Y AJUSTAR',title:'Puesta en marcha y agenda de apertura',owner:'Equipo completo',deliverable:'Ensayos internos, incidencias resueltas, obligaciones de apertura cumplidas, agenda inicial y caja revisada a 13 semanas.',condition:'Reservar margen de calendario por vacaciones de proveedores; no programar el montaje crítico para finales de agosto.',tasks:[{id:'commissioning',name:'Verificar puesta en servicio y requisitos industriales y municipales'},{id:'first-bookings',name:'Convertir contactos en citas fechadas compatibles con la capacidad inicial'},{id:'go-no-go',name:'Revisar las seis condiciones de apertura y fijar fecha definitiva'}]},
    {date:'Sep–dic 2028',subtitle:'ABRIR Y APRENDER',title:'Apertura progresiva, revisión semanal',owner:'Carlos + jefe de taller',deliverable:'Control semanal de caja a 13 semanas, horas vendidas, margen por trabajo, retrabajos y agenda; revisión a 30/60/90 días.',condition:'Aumentar la carga después de demostrar calidad y cumplimiento de plazos. Si falta demanda, corregir captación antes de comprar más equipo.',tasks:[{id:'opening',name:'Abrir con agenda limitada y supervisión efectiva'},{id:'weekly-kpis',name:'Revisar caja, productividad, calidad y satisfacción cada semana'},{id:'90days',name:'Evaluar recepción, alcance y necesidades a los 90 días'}]}
  ],
  gates:[
    {title:'Personas y competencia',text:'Jefe incorporado, funciones pactadas, supervisión y sustitución previstas. Los socios ejecutan solo tareas para las que estén preparados.'},
    {title:'Capital y deuda',text:'Aportaciones disponibles y financiación documentada. El escenario adverso mantiene la reserva acordada, sin ayudas o indemnizaciones supuestas.'},
    {title:'Local e instalaciones',text:'Compatibilidad confirmada, obra terminada, documentación técnica y obligaciones de actividad e industria resueltas para ese establecimiento.'},
    {title:'Herramientas y suministro',text:'Equipos puestos en servicio, soporte, recambios, documentación técnica y accesos de diagnosis adecuados al catálogo de trabajos.'},
    {title:'Demanda y agenda',text:'Clientes identificados y citas con trabajos y fechas reales. La cantidad se deriva de horas y tickets, no de una cuota imaginada del parque.'},
    {title:'Calidad y protección',text:'Presupuestos, autorizaciones, custodia, prevención, residuos, garantías, seguros y comprobaciones de entrega operativos.'}
  ]
};
