/* Datos de planificación revisados el 13-09-2026. Todos los importes base son netos.
 * Un precio público no es una oferta ni una validación de idoneidad técnica.
 * financed indica una hipótesis elegible en el escenario, nunca crédito concedido.
 * lifeMonths es vida contable de trabajo a revisar; no es una tabla fiscal.
 */
window.WorkshopTechnical = {
  asOf: '2026-09-13',
  currency: 'EUR',
  priceBasis: 'Euros de 2026 sin IVA. Actualizar y pedir ofertas para 2028.',
  equipmentRange: { low: 30000, high: 55000, basis: 'Estimación propia de planificación; no techo garantizado.' },
  equipment: [
    { id: 'lift-low', name: 'Elevador 4,2 t de perfil bajo · referencia TW242PE', quantity: 1, unitPrice: 2189.26, amount: 2189.26, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Elevación', status: 'Precio público', reason: 'Referencia 96 mm, 400 V. Validar deportivos, apoyos, plano y solera con instalador; no todos los Porsche caben por definición.', source: { title: 'Twin Busch TW242PE-400', url: 'https://www.twinbusch.es/product_info.php?products_id=4' }, exclusions: 'IVA; portes publicados 199 €; instalación, descarga, obra y comprobación de cimentación. Portes y montaje provisionados en otra partida.' },
    { id: 'lift-suv', name: 'Elevador 5 t para puesto SUV · referencia TW250', quantity: 1, unitPrice: 3139.67, amount: 3139.67, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Elevación', status: 'Precio público', reason: 'Segundo puesto con margen de capacidad. Validar geometría, distribución de pesos, altura y adaptadores por vehículo.', source: { title: 'Twin Busch TW250-400-G', url: 'https://www.twinbusch.es/product_info.php?products_id=415' }, exclusions: 'IVA; portes publicados 269 €; montaje, descarga y obra. No sustituye validación técnica del vehículo.' },
    { id: 'compressor', name: 'Compresor 250 L · referencia TWKL-250', quantity: 1, unitPrice: 1197.52, amount: 1197.52, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Aire comprimido', status: 'Precio público', reason: 'Dimensionar con instalador por caudal útil, ruido, presión y uso simultáneo. Red y tratamiento separados.', source: { title: 'Twin Busch compresor 250 L', url: 'https://www.twinbusch.es/product_info.php?products_id=372' }, exclusions: 'IVA; portes publicados 69 €; acometida, tratamiento de aire, red y legalización cuando proceda.' },
    { id: 'tool-carts', name: 'Carros básicos con 181 herramientas', quantity: 2, unitPrice: 345, amount: 690, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Herramientas', status: 'Precio público', reason: 'Referencia inicial de EquipoTaller; utillaje específico, calidad profesional requerida y piezas faltantes se validan con el jefe.', source: { title: 'EquipoTaller 10/TBR5807-X', url: 'https://www.equipotaller.es/es/carros-de-herramientas/653-carro-de-herramientas-con-7-cajones-8436610711807.html' }, exclusions: 'IVA y portes. Herramientas Porsche, dinamometría y equipos de medición adicionales.' },
    { id: 'oil-recovery', name: 'Recuperadores de aceite 70 L · TW20850', quantity: 2, unitPrice: 197.52, amount: 395.04, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Fluidos', status: 'Precio público', reason: 'Un recuperador por puesto. Almacenamiento separado y gestión de residuos previstos aparte.', source: { title: 'Twin Busch equipamiento · TW20850', url: 'https://www.twinbusch.es/index.php?cPath=10' }, exclusions: 'IVA; portes publicados 49 € por unidad, a confirmar agrupados. Gestor de residuos y recipientes finales.' },
    { id: 'multibrand-diagnostic', name: 'Diagnosis multimarca · referencia Autel MS906 Pro', quantity: 1, unitPrice: 1231.4, amount: 1231.4, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 48, category: 'Diagnosis', status: 'Precio público', reason: 'Neto calculado desde 1.489,99 € con IVA. Confirmar licencia europea, soporte y cobertura por VIN; no sustituye PIWIS.', source: { title: 'Autodiag · Autel MS906 Pro', url: 'https://autodiag.es/product/autel-ms906-pro/' }, exclusions: 'IVA, renovaciones, accesos OEM y funciones no cubiertas. Transporte y plazo de licencia a confirmar.' },
    { id: 'battery-support', name: 'Fuente estabilizada 12 V para diagnosis', quantity: 1, unitPrice: 900, amount: 900, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Diagnosis', status: 'Estimación propia', reason: 'Referencia GYSFLASH 100-12 HF: 789 € visibles, sin base fiscal inequívoca en el texto. Se reserva 900 € netos, no precio cotizado.', source: { title: 'AutoTuner · GYSFLASH 100-12 HF, referencia funcional', url: 'https://www.autotuner.com/es/products/gysflash-100-12-hf' }, exclusions: 'IVA y portes. Validar capacidad y compatibilidad con la operación y batería; no es equipo para batería de propulsión HV.' },
    { id: 'special-tools', name: 'Herramientas profesionales y utillaje Porsche adicional', quantity: 1, unitPrice: 4500, amount: 4500, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Herramientas', status: 'Estimación propia', reason: 'Vasos especiales, extractores, fijación, distribución seleccionada y herramienta eléctrica. Lista final del jefe según servicios y generaciones.', source: { title: 'Estimación propia · pendiente de lista y ofertas', url: '' }, exclusions: 'IVA. No cubre toda la gama Porsche, reconstrucciones completas, todos los motores ni todas las cajas.' },
    { id: 'metrology', name: 'Dinamometría, medición y comprobación', quantity: 1, unitPrice: 1500, amount: 1500, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Control de calidad', status: 'Estimación propia', reason: 'Llaves de par, multímetro, manómetros y medición mecánica seleccionados por rango; plan de calibración/verificación aparte.', source: { title: 'Estimación propia · selección del jefe técnico', url: '' }, exclusions: 'IVA, renovaciones de calibración y equipo HV especializado.' },
    { id: 'jacks-supports', name: 'Gatos, soportes, prensa y ayuda a manipulación', quantity: 1, unitPrice: 2200, amount: 2200, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 96, category: 'Elevación', status: 'Estimación propia', reason: 'Dotación complementaria para ruedas, suspensión y mecánica acotada. Dimensionar herramientas por carga y uso.', source: { title: 'Estimación propia · presupuesto pendiente', url: '' }, exclusions: 'IVA y traslado. No mesa de desmontaje de batería HV ni equipamiento de reconstrucción integral.' },
    { id: 'brake-service', name: 'Purgado de frenos y adaptadores', quantity: 1, unitPrice: 900, amount: 900, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Fluidos', status: 'Estimación propia', reason: 'Equipo y adaptadores compatibles con procedimientos Porsche; validar funciones electrónicas necesarias.', source: { title: 'Estimación propia · presupuesto pendiente', url: '' }, exclusions: 'IVA, líquido de frenos, discos/pastillas y formación.' },
    { id: 'fluid-service', name: 'Refrigeración y trasvase de fluidos', quantity: 1, unitPrice: 800, amount: 800, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Fluidos', status: 'Estimación propia', reason: 'Vacío/llenado, bandejas y adaptadores de servicio; evitar contaminación cruzada.', source: { title: 'Estimación propia · presupuesto pendiente', url: '' }, exclusions: 'IVA. Sin estación de aire acondicionado, lavado universal de cajas ni servicio HV.' },
    { id: 'benches-storage', name: 'Bancos, armarios y estanterías de taller', quantity: 1, unitPrice: 1600, amount: 1600, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Instalación', status: 'Estimación propia', reason: 'Almacenamiento, banco de trabajo y preparación de piezas; disposición final según plano.', source: { title: 'Estimación propia · presupuesto pendiente', url: '' }, exclusions: 'IVA, mobiliario decorativo y obra.' },
    { id: 'air-network', name: 'Red de aire, filtrado y secado', quantity: 1, unitPrice: 1500, amount: 1500, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Aire comprimido', status: 'Estimación propia', reason: 'Separado del compresor; planificar condensados, puntos de uso e instalación segura.', source: { title: 'Estimación propia · oferta de instalador pendiente', url: '' }, exclusions: 'IVA, adecuaciones eléctricas importantes y trámites de obra.' },
    { id: 'exhaust-extraction', name: 'Extracción localizada de gases de escape', quantity: 1, unitPrice: 2200, amount: 2200, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Seguridad', status: 'Estimación propia', reason: 'Reserva de equipo; trazado, ventilación y salida se definen en el proyecto del local.', source: { title: 'Estimación propia · proyecto y oferta pendientes', url: '' }, exclusions: 'IVA. Obras especiales de conductos o salida, permisos y ventilación general no están garantizados por esta cifra.' },
    { id: 'waste-containment', name: 'Recipientes de residuos y contención de derrames', quantity: 1, unitPrice: 800, amount: 800, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 60, category: 'Seguridad', status: 'Estimación propia', reason: 'Aceite usado, filtros, líquidos y absorbentes: separación y cubetos según evaluación. La fuente acredita el trámite, no el coste.', source: { title: 'Comunidad de Madrid · productores de residuos peligrosos', url: 'https://sede.comunidad.madrid/comunicaciones-declaraciones/productores-residuos-peligrosos' }, exclusions: 'IVA, tasas, retirada por gestor y consumibles recurrentes.' },
    { id: 'ppe-safety', name: 'Protección, señalización y primeros auxilios iniciales', quantity: 1, unitPrice: 900, amount: 900, vatRate: 0.21, financed: false, depreciable: false, lifeMonths: 0, category: 'Seguridad', status: 'Estimación propia', reason: 'Dotación inicial a concretar por prevención. Equipos de consumo tratados como gasto inicial, no activo amortizable.', source: { title: 'Estimación propia · evaluación preventiva pendiente', url: '' }, exclusions: 'IVA, servicio de prevención, formación y protección contra incendios exigida por proyecto.' },
    { id: 'it-workstation', name: 'Puesto informático, red e impresión', quantity: 1, unitPrice: 1500, amount: 1500, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 48, category: 'Gestión', status: 'Estimación propia', reason: 'Recepción, órdenes de reparación y documentación técnica. Software recurrente presupuestado aparte.', source: { title: 'Estimación propia · presupuesto pendiente', url: '' }, exclusions: 'IVA, cuotas de programas, conexión y cámaras/alarma si se añaden.' },
    { id: 'delivery-installation', name: 'Portes, descarga e instalación de equipos', quantity: 1, unitPrice: 2400, amount: 2400, vatRate: 0.21, financed: true, depreciable: true, lifeMonths: 120, category: 'Instalación', status: 'Estimación propia', reason: 'Bolsa conjunta: incluye portes de los equipos anteriores y montaje/puesta en servicio. Imputar al activo correspondiente al contabilizar.', source: { title: 'Estimación propia · cotización integral pendiente', url: '' }, exclusions: 'IVA y refuerzos de solera/obra. No sumar de nuevo los portes mencionados en cada ficha.' },
    { id: 'porsche-diagnostic-reserve', name: 'Provisión de solución oficial de diagnosis Porsche', quantity: 1, unitPrice: 9000, amount: 9000, vatRate: 0.21, financed: false, depreciable: false, lifeMonths: 0, category: 'Diagnosis', status: 'Provisión sin cotizar', reason: 'No hay precio español completo verificado. Reserva de financiación, no activo contratado: confirmar hardware, acceso y modalidad; sustituir por oferta.', source: { title: 'Porsche PCSS/PPN · acceso de independientes, sin tarifa pública verificada', url: 'https://pcss-tsi.porsche.com/landing/static/assets/files/ES/general.html' }, exclusions: 'IVA y costes que excedan la reserva. Licencias mensuales aparte como hipótesis; reconciliar oferta para no duplicar gasto.' }
  ],
  premisesEstimates: [
    { id: 'fitout', name: 'Adecuación de un local aprovechable', low: 20000, base: 30000, high: 50000, vatRate: 0.21, status: 'Estimación propia, sin visita ni presupuesto', exclusions: 'No incluye maquinaria, fianza, traspaso ni caja. Deficiencias importantes pueden superar el intervalo.' },
    { id: 'engineering', name: 'Ingeniería, proyecto y legalizaciones', low: 3000, base: 4500, high: 7000, vatRate: 0.21, status: 'Estimación propia, sin oferta', exclusions: 'Tasas municipales y actuaciones extraordinarias según emplazamiento.' }
  ],
  operatingAllowances: [
    { id: 'porsche-information', name: 'Porsche: licencias e información técnica', monthlyNet: 350, status: 'Estimación propia; tarifa oficial pendiente', source: 'porsche-rmi', note: 'No promesa de acceso ni coste oficial. Reconciliar con provisión inicial según compra/alquiler/suscripción.' },
    { id: 'multibrand-renewal', name: 'Renovación de diagnosis multimarca', monthlyNet: 50, status: 'Estimación propia; duración incluida pendiente', source: 'autel-reference', note: 'Activar al terminar el periodo incluido; no duplicar cuotas.' }
  ],
  qualifications: [
    { id: 'masterd', name: 'Confirmar la vía de titulación MasterD', status: 'Pendiente de documentación personal', text: 'La URL prepara pruebas libres. 1.620 h y 24 meses de curso no equivalen a título oficial ya concedido ni garantizan fecha de FCT/proyecto.', source: 'masterd', action: 'Revisar contrato, matrícula, acceso académico, convocatorias y reconocimiento de prácticas en otoño de 2026.' },
    { id: 'fp-calendar', name: 'Separar exámenes, FCT/proyecto y título', status: 'Calendario 2027–2028 por publicar/verificar', text: 'La convocatoria Madrid 2025–2026 situó FCT/proyecto en el trimestre inicial del curso siguiente. No prometer título en junio de 2028.', source: 'madrid-fp', action: 'Confirmar con el centro examinador el itinerario completo antes de fijar dependencia con apertura.' },
    { id: 'technical-chief', name: 'Contratar y validar al jefe de taller Porsche', status: 'Hito crítico de apertura', text: 'Los socios no tienen experiencia de taller. Valorar trabajos reales por generación, referencias, diagnosis, seguridad y capacidad de enseñar y controlar calidad.', source: 'workshop-law', action: 'Incorporar al profesional antes de cerrar cartera de servicios, lista de equipos y procedimientos.' },
    { id: 'industrial', name: 'Cumplimiento industrial y municipal', status: 'Pendiente de local', text: 'El titular presenta declaración responsable y mantiene medios/documentación. La FP no es el permiso de actividad del local; revisar además vía municipal y proyecto.', source: 'madrid-workshop', action: 'Informe técnico de viabilidad del local antes del alquiler y documentación completa antes de abrir.' },
    { id: 'refrigerant', name: 'Certificación para refrigerantes de climatización', status: 'Requerida según trabajos', text: 'Las operaciones reguladas con refrigerantes fluorados requieren certificado personal específico. No cubrirlas solo con una máquina.', source: 'fluorinated-gases', action: 'Acreditar personal o subcontratar el servicio.' },
    { id: 'electric-risk', name: 'Formación y procedimiento para híbridos/eléctricos', status: 'Evaluación preventiva necesaria', text: 'También para aceptar trabajos periféricos: identificar riesgos, límites y puntos de elevación por vehículo. Sin reparación inicial de batería o circuito de propulsión HV.', source: 'insst-electrical', action: 'Servicio de prevención y jefe definen formación, autorización, herramientas y operaciones admitidas.' },
    { id: 'oem-access', name: 'Acceso oficial a información y diagnosis', status: 'Acreditación y oferta pendientes', text: 'PPN/PCSS permiten acceso independiente. Diagnosis exige acreditación/acuerdos; las suscripciones y el equipo deben contratarse por el canal oficial.', source: 'porsche-rmi', action: 'Obtener requisitos y oferta española de hardware, alta, renovaciones y funciones antes de aprobar inversión.' }
  ],
  scope: [
    { id: 'launch-size', name: '250–350 m² y dos elevadores', phase: 'Apertura', text: 'Hipótesis de búsqueda, no mínimo legal. Validar maniobra, parking, solera, estructura, potencia, accesos y distribución.' },
    { id: 'core', name: 'Mantenimiento y mecánica Porsche acotada', phase: 'Apertura', text: 'Aceite/filtros, frenos, inspecciones, diagnosis y reparaciones dominadas por el jefe. Definir generaciones y exclusiones.' },
    { id: 'subcontract', name: 'Neumáticos, alineación y ADAS con colaboradores', phase: 'Subcontratar al inicio', text: 'Acordar precio, margen, citas, traslados y responsabilidad. Internalizar cuando demanda y capacidad lo justifiquen.' },
    { id: 'defer', name: 'Trabajos complejos y carrocería', phase: 'Posterior o colaborador', text: 'Sin pintura, restauración integral, reconstrucción general de motores/cajas, competición ni batería de propulsión HV en el alcance inicial.' },
    { id: 'brand-limits', name: 'Porsche y Audi no son equivalencias de reparación', phase: 'Selección técnica', text: 'Experiencia VAG es complementaria. Panamera PDK y RS6 tiptronic ilustran diferencias; validar todo por VIN, generación y operación.' },
    { id: 'dates', name: 'Junio condicionado · septiembre 2028 objetivo', phase: 'Calendario', text: 'Apertura solo con local apto, financiación, jefe incorporado, equipos/proveedores y trámites completos. La fecha de título no se presume.' }
  ],
  financeNotes: [
    { name: 'ICO', text: 'El banco decide concesión, importe y garantías. La ficha consultada es de 2026; no garantiza disponibilidad ni aprobación en 2028.', source: 'ico' },
    { name: 'Indemnización', text: 'Recurso contingente hasta acuerdo y cobro. No contarlo como dinero disponible en el escenario base.' }
  ],
  sources: [
    { id: 'masterd', title: 'MasterD · preparación de pruebas libres Automoción', url: 'https://www.masterd.es/fp-tecnico-superior-automocion', type: 'Proveedor de formación', checkedAt: '2026-09-13' },
    { id: 'madrid-fp', title: 'Comunidad de Madrid · pruebas de obtención de títulos', url: 'https://www.comunidad.madrid/educacion/pruebas-obtencion-titulos-tecnico-tecnico-superior-fp', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'official-degree', title: 'TodoFP · Técnico Superior en Automoción', url: 'https://www.todofp.es/que-estudiar/familias-profesionales/transporte-mantenimiento-vehiculos/automocion.html', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'workshop-law', title: 'BOE · RD 1457/1986, talleres', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-1986-18896', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'madrid-workshop', title: 'Comunidad de Madrid · declaración responsable de taller', url: 'https://sede.comunidad.madrid/comunicaciones-declaraciones/talleres-reparacion-vehiculos', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'fire-code', title: 'BOE · RD 164/2025, incendios industriales', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2025-7190', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'hazardous-waste', title: 'Comunidad de Madrid · productores de residuos peligrosos', url: 'https://sede.comunidad.madrid/comunicaciones-declaraciones/productores-residuos-peligrosos', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'fluorinated-gases', title: 'Comunidad de Madrid · habilitación gases fluorados', url: 'https://www.comunidad.madrid/industria/habilitacion-empresas-profesionales-relacionados-gases-fluorados', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'insst-electrical', title: 'INSST · riesgo eléctrico', url: 'https://www.insst.es/materias/riesgos/seguridad-en-el-trabajo/riesgo-electrico', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'porsche-rmi', title: 'Porsche · PCSS/PPN para talleres independientes', url: 'https://pcss-tsi.porsche.com/landing/static/assets/files/ES/general.html', type: 'Fabricante', checkedAt: '2026-09-13' },
    { id: 'lift-low-reference', title: 'Twin Busch TW242PE-400 · 2.189,26 € netos', url: 'https://www.twinbusch.es/product_info.php?products_id=4', type: 'Precio público de proveedor', checkedAt: '2026-09-13' },
    { id: 'lift-suv-reference', title: 'Twin Busch TW250-400-G · 3.139,67 € netos', url: 'https://www.twinbusch.es/product_info.php?products_id=415', type: 'Precio público de proveedor', checkedAt: '2026-09-13' },
    { id: 'compressor-reference', title: 'Twin Busch TWKL-250 · 1.197,52 € netos', url: 'https://www.twinbusch.es/product_info.php?products_id=372', type: 'Precio público de proveedor', checkedAt: '2026-09-13' },
    { id: 'cart-reference', title: 'EquipoTaller carro con 181 herramientas · 345 € netos', url: 'https://www.equipotaller.es/es/carros-de-herramientas/653-carro-de-herramientas-con-7-cajones-8436610711807.html', type: 'Precio público de proveedor', checkedAt: '2026-09-13' },
    { id: 'oil-reference', title: 'Twin Busch TW20850 · 197,52 € netos', url: 'https://www.twinbusch.es/index.php?cPath=10', type: 'Precio público de proveedor', checkedAt: '2026-09-13' },
    { id: 'autel-reference', title: 'Autodiag Autel MS906 Pro · 1.489,99 € con IVA', url: 'https://autodiag.es/product/autel-ms906-pro/', type: 'Precio público de vendedor', checkedAt: '2026-09-13' },
    { id: 'battery-reference', title: 'AutoTuner GYSFLASH · 789 € visibles, IVA por confirmar', url: 'https://www.autotuner.com/es/products/gysflash-100-12-hf', type: 'Referencia de proveedor; base fiscal no confirmada', checkedAt: '2026-09-13' },
    { id: 'panamera-pdk', title: 'Porsche · Panamera 2024, transmisión PDK', url: 'https://newsroom.porsche.com/en_AU/2024/products/porsche-panamera-product-highlights-36377.html', type: 'Fabricante', checkedAt: '2026-09-13' },
    { id: 'rs6-tiptronic', title: 'Audi · transmisión RS6 performance', url: 'https://www.audi.com/en/the-audi-rs-6-avant-and-the-new-audi-rs-6-avant-performance-12345/transmission-12349', type: 'Fabricante', checkedAt: '2026-09-13' },
    { id: 'ico', title: 'ICO · Empresas y Emprendedores 2026', url: 'https://www.ico.es/documents/20124/39709/Ficha%2Blarga%2B%2BICO%2BEmpresas%2By%2Bemprendedores.pdf/3121c305-e262-cfb5-95ee-962a7bf0eb8f?download=true&t=1769070471284', type: 'Oficial', checkedAt: '2026-09-13' },
    { id: 'dgt-service-book', title: 'DGT · Libro electrónico de mantenimiento voluntario', url: 'https://www-pro.dgt.es/nuestros-servicios/tu-vehiculo/tus-vehiculos/libro-electronico-de-mantenimiento/', type: 'Oficial', checkedAt: '2026-09-13' }
  ]
};
